# See http://www.appveyor.com/docs/appveyor-yml for many more options
environment:
  NuGetApiKey:
    secure: FxzJKr/gizug7YODGAEmnYDBFobOXGw6s42SGrzWbmNX425um1JC3WCZWFph32qz

os:
  - "WMF 5"

branches:
  only:
    - master

# Skip on updates to the readme.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message
skip_commits:
  message: /updated readme.*/

install:
  - ps: |
      Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force | Out-Null
      Install-Module Pester -MinimumVersion 3.4.0 -Scope CurrentUser -Force | Out-Null
      Install-Module psake -Scope CurrentUser -Force | Out-Null
      Install-Module PSScriptAnalyzer -Scope CurrentUser -Force | Out-Null
      Install-Module platyPS -Scope CurrentUser -Force | Out-Null


build_script:
  - ps: |
      $testResultsFile = Join-Path $pwd -ChildPath "$PSScriptRoot/TestResults.xml"
      Invoke-psake build.psake.ps1 -taskList Test, BuildHelp -properties @{"TestOutputFile" = $testResultsFile}
      if ($psake.build_success -and (Test-Path $testResultsFile)) {
          (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", $testResultsFile)
      }
      else {
          # Terminate the script to fail the build
          $Error | Format-List * -Force
          exit 1;
      }

on_finish:
    - ps: |
        # Publish the contents of the Release folder
        Add-Type -assemblyname System.IO.Compression.FileSystem
        $zipPath = "$pwd\Plaster.zip"
        [System.IO.Compression.ZipFile]::CreateFromDirectory("$pwd\Release", $zipPath)
        Push-AppveyorArtifact $zipPath

#test_script:
# temporary to get build process working again... install pester and add to psmodulepath
#  - ps: . .\build.ps1
# Test with native PS version
#  - ps: . .\Tests\appveyor.pester.ps1 -Test
# Finalize pass - collect and upload results
#  - ps: . .\Tests\appveyor.pester.ps1 -Finalize